Making ParseError and ValidationError public
fmeringdal/rust-rrule pull request #102
Opened 2024-02-04 05:38 UTC by msdrigg

- Solves #101

2024-02-04 05:54 UTC, msdrigg commented
I tested this in my own repo and it's working.

2024-02-04 16:19 UTC, fmeringdal commented
LGTM! Make sure to add an entry in `CHANGELOG.md` that these errors are made public and then this should be good to merge

2024-02-04 23:12 UTC, msdrigg commented
Done

2024-02-05 14:38 UTC, fmeringdal requested changes

2024-02-05 14:38 UTC, fmeringdal commented on CHANGELOG.md
> +- Make `ParseError` and `ValidationError` public
This needs to be added to the `0.12.0` entry as that is the next version to be released

2024-02-05 16:26 UTC, merged