Change the return type of `RRuleSet::all` to a struct
fmeringdal/rust-rrule pull request #82
Opened 2022-08-22 18:13 UTC by omid

Fix #80 
@fmeringdal is “limited” a correct wording? I still don't know its use case :)
Isn't “truncated” better?

Fix #64
I didn't test it, but don't forget to add your API token as `CARGO_REGISTRY_TOKEN` in the repo Settings > Secrets > Actions

2022-08-23 18:53 UTC, fmeringdal requested changes
Great stuff! Some minor comments, I will make sure to add the cargo secret to the repo secrets.

2022-08-23 18:53 UTC, fmeringdal commented on CHANGELOG.md
> +- `RRuleSet::all` returns an `RRuleSetResult` struct instead of a tuple.
`RRuleSetResult` seems a little long, maybe simplify it to `RRuleResult`?

2022-08-23 18:53 UTC, fmeringdal commented on rrule/src/core/rruleset.rs
> +    pub list: Vec<DateTime>,
How about `dates` rather than `list`?

2022-08-23 21:22 UTC, omid commented
Thanks @fmeringdal 
What about my first comment/question?

> @fmeringdal is “limited” a correct wording? I still don't know its use case :)
Isn't “truncated” better?

2022-08-24 19:53 UTC, fmeringdal commented
I think limited is a good enough term as it tells that the result is "limited" and could potentially contain more dates and the iteration was "limited" to avoid infinite loops. Open to other suggestions, but I still think limited is more accurate than truncated.

2022-08-25 08:50 UTC, omid commented
@fmeringdal cool, np, will add more doc comment soon, and then I'm good I think

2022-08-25 19:15 UTC, fmeringdal commented
Looks good! Only need to update the example in the README and it should be good to merge

2022-08-25 21:15 UTC, fmeringdal commented
Thanks @omid !

2022-08-25 21:15 UTC, merged